### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by thanhquanky** [steelbrain/Atom-Hack#35]
Uncaught SyntaxError: Unexpected end of input

**Atom Version**: 0.158.0
**System**: linux 3.13.0-24-generic
**Thrown From**: [Atom-Hack](https://github.com/steelbrain/atom-hack) package, v3.2.0

### Steps To Reproduce

1. I accidentally remove a character, so I add it back and save it. Then the error showed up.

### Stack Trace

```
At file:///usr/share/atom/resources/app/static/index.html?loadSettings=%7B%22bootstrapScript%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.158.0%22%2C%22shellLoadTime%22%3A300%7D:1

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at Linter.module.exports.Linter.setErrors (/home/thanhquanky/.atom/packages/Atom-Hack/lib/linter.coffee:38:25)
  at /home/thanhquanky/.atom/packages/Atom-Hack/lib/linter.coffee:22:12
  at ChildProcess.exithandler (child_process.js:752:5)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1013:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1085:5)

```

/cc @atom/core

**Comment by steelbrain** [comment]
Are you using a remote server or a local one?

**Comment by thanhquanky** [comment]
I use local server

**Comment by steelbrain** [comment]
Okay, so run `pkill hh_server` and then post the output of `hh_client` in the project directory.

**Comment by steelbrain** [comment]
Closing due to inactivity.
