### ISSUE TITLE
Failed to activate the Atom-Hack package

### ISSUE THREAD

**Issue by mcrumm** [steelbrain/Atom-Hack#64]
I get this error every time I open Atom.

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [Atom-Hack](https://github.com/steelbrain/atom-hack) package, v3.5.4

### Stack Trace

Failed to activate the Atom-Hack package

```
At undefined is not a function

TypeError: undefined is not a function
    at module.exports (/Users/mike/.atom/packages/Atom-Hack/lib/tooltip-view.coffee:10:14)
    at Object.module.exports.activate (/Users/mike/.atom/packages/Atom-Hack/lib/init.coffee:28:45)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "Atom-Hack": {
    "enableTypeChecking": false
  }
}
```

### Installed Packages

```coffee
# User
Atom-Hack, v3.5.4
autocomplete-hack, v0.2.3
language-hack, v0.1.1
language-puppet, v0.12.0
linter-puppet-lint, v0.2.9

# Dev
No dev packages
```

**Comment by mauriciord** [comment]
Same for me !

**Comment by steelbrain** [comment]
I have a working rewrite branch, it doesn't support SSH though.

**Comment by steelbrain** [comment]
I'll try to get it done now.
