### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/nuclide:'

### ISSUE THREAD

**Issue by latamautos** [steelbrain/Atom-Hack#77]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [Atom-Hack](https://github.com/steelbrain/atom-hack) package, v6.1.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/nuclide:'

```
At ATOM_SHELL_ASAR.js:118

Error: ENOENT: no such file or directory, lstat '/nuclide:'
  at Error (native)
  at fs.lstatSync (fs.js:844:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
  at Object.realpathSync (fs.js:1449:21)
  at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
  at /Users/mpirez/.atom/packages/Atom-Hack/lib/base.js:55:35
  at Hack.readConfig (/Users/mpirez/.atom/packages/Atom-Hack/lib/base.js:94:11)
  at /Users/mpirez/.atom/packages/Atom-Hack/lib/base.js:38:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:279:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:908:41
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:441:16)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -0:57 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:48.1.0 nuclide-quick-open:toggle-omni-search (atom-pane.pane.active)
     -0:41.7.0 tabs:keep-preview-tab (atom-text-editor.editor)
     -0:39.6.0 nuclide-click-to-symbol:activate (atom-text-editor.editor.is-focused)
     -0:39.4.0 nuclide-quick-open:toggle-omni-search (atom-text-editor.editor.is-focused)
     -0:31.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:31.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:28.8.0 nuclide-remote-projects:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:27.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -0:24.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:10.1.0 nuclide-quick-open:toggle-omni-search (ul.list-inline.tab-bar.inset-panel)
     -0:08.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:08.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:04.9.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view",
      "autocomplete-hack"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Atom-Hack, v6.1.5
hyperclick, v0.0.0
language-hack, v0.1.1
linter, v1.9.1
nuclide-arcanist, v0.0.0
nuclide-blame, v0.0.0
nuclide-blame-provider-hg, v0.0.0
nuclide-blame-ui, v0.0.0
nuclide-buck-files, v0.0.0
nuclide-busy-signal, v0.0.0
nuclide-clang-atom, v0.0.0
nuclide-click-to-symbol, v0.0.22
nuclide-code-format, v0.0.0
nuclide-debugger-atom, v0.0.0
nuclide-debugger-hhvm, v0.0.0
nuclide-debugger-lldb, v0.0.0
nuclide-debugger-node, v0.0.0
nuclide-diagnostics-store, v0.0.0
nuclide-diagnostics-ui, v0.0.0
nuclide-diff-view, v0.0.0
nuclide-file-tree, v0.0.0
nuclide-file-watcher, v0.0.0
nuclide-find-references, v0.0.0
nuclide-flow, v0.0.0
nuclide-fuzzy-filename-provider, v0.0.0
nuclide-hack, v0.0.0
nuclide-hack-symbol-provider, v0.0.0
nuclide-health, v0.0.0
nuclide-hg-repository, v0.0.0
nuclide-home, v0.0.0
nuclide-installer, v0.0.0
nuclide-language-hack, v0.0.0
nuclide-objc, v0.0.0
nuclide-ocaml, v0.0.0
nuclide-open-filenames-provider, v0.0.0
nuclide-quick-open, v0.0.0
nuclide-recent-files-provider, v0.0.0
nuclide-recent-files-service, v0.0.0
nuclide-remote-projects, v0.0.0
nuclide-test-runner, v0.0.0
nuclide-toolbar, v0.0.0
nuclide-type-hint, v0.0.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
I am sorry but `atom-hack` doesn't work with nuclide's remote server feature, it would be a lot of work to add that support. so I am waiting for someone from the community to develop a open-source well-licensed nuclide-alternative remote tree view and then I'll add support for it :)
